# Generated by Django 6.0.4 on 2026-05-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('adresse', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
    ]
