# Generated by Django 6.0.4 on 2026-05-07 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('EXPEDIE', 'Expédié'), ('EN_COURS_DE_LIVRAISON', 'En cours de livraison'), ('LIVRE', 'Livré')], max_length=30, unique=True)),
                ('description_etape', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField()),
                ('date_envoi', models.DateField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis_recus', to='client.client')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis_envoyes', to='client.client')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colis.statut')),
            ],
        ),
    ]
